# Generated by Django 3.2.9 on 2022-02-08 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashback', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='feedbackus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=0)),
                ('recommendation', models.CharField(max_length=50)),
                ('service', models.CharField(max_length=50)),
                ('msg', models.TextField()),
            ],
        ),
    ]
