# Generated by Django 3.1.7 on 2022-02-08 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='cashback',
            field=models.IntegerField(default=0),
        ),
    ]
